//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWDW_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int deviceId { get; set; }
        public string deviceName { get; set; }
        public Nullable<int> roomId { get; set; }
        public Nullable<int> deviceStatus { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual Room Room { get; set; }
    }
}
