//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWDW_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int recordId { get; set; }
        public Nullable<int> deviceId { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
        public string image { get; set; }
        public Nullable<int> recordStatus { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
