//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWDW_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserLocations = new HashSet<UserLocation>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<int> gender { get; set; }
        public string deviceToken { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLocation> UserLocations { get; set; }
    }
}
